baseURL = "www.swalog.ch"
languageCode = "en-us"
title = "Swalog"
theme = "hyde"

[author]
name = "Alexander Hoffmann"

[params]
layoutReverse = true
description= "Journal, \"thoughts on X\", ongoing projects."
sectionPagesMenu="main"
